blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('',views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:slug>', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('create/', views.create_post, name='createpost'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from .managers import PublishedManager

# Create your models here.


class Post(models.Model):
    STATUS_CHOICES = (
    ('draft','Draft'),
    ('published', 'Published')
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.CharField(max_length=40)
    # author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', null=True)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')
    objects = models.Manager()
    published = PublishedManager() 

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', 
                       args=[ self.publish.year,
                              self.publish.month,
                              self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField(default=None)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from dataclasses import field
from pyexpat import model
from django import forms
from .models import Comment, Post

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    recepient = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):


    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm, CommentForm
from django.core.mail import send_mail

# Create your views here.

def post_list(request):
    all_post = Post.published.all()
    
    paginator = Paginator(all_post, 5)
    page = request.GET.get('page')


    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver the last page of results
        posts = paginator.page(paginator.num_pages)



    data = {
        'posts':posts
    }

    return render (request, 'blog/post/list.html', data)







def post_detail(request, year, month, day, slug):
    post = get_object_or_404(Post, slug=slug, status='published', publish__year=year, publish__month=month, publish__day=day)

    #List of active comments for this post
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()


    return render (request, 'blog/post/detail.html', {'post':post,
      'comments':comments,
      'new_comment':new_comment,
      'comment_form':comment_form})



def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')

    sent=False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        # Form was submitted
        if form.is_valid():
            #Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            # post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = f"{cd['name']} recommends you read" f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n {cd['name']}\'s comments:{cd['comments']}"

            send_mail(subject, message, "Ralu from Astroverse <admin@admin.com>", [cd['recepient']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request, 'blog/post/share.html', 
                      {'post':post,
                      'form':form,
                      'sent':sent})

def create_post(request):
    if request.method == 'POST':
        if request.POST.get('title') and request.POST.get('content'):
            post=Post()
            post.title = request.POST.get('title')
            post.body = request.POST.get('content')
            post.person = request.POST.get('author_name')
            post.slug=post.title.lower().replace(" ","-")
            post.save()

            return redirect('blog:post_list')
        else:
            pass
    return render(request, 'create.html')

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <title>
    {% block title %}
    
    {% endblock %}
  </title>
  <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>
<body>
  <div id="content">
    {% block body %}
    
    {% endblock body %}
  </div>
  <div id="sidebar">
    <h2>My blog</h2>
    <p>This is my blog.</p>
  </div>
</body>
</html>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
    </span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
   {% block title %}
   {{ post.title }}
   {% endblock %}

  {% block body %}
     <h1>{{ post.title }}</h1>
     <p class="date">
       Published {{ post.publish }} by {{ post.author }}
     </p>
     {{ post.body|linebreaks }}
     <p>
         <a href="{% url 'blog:post_share' post.id %}">
             Share This Post
         </a>
     </p>
     {% with comments.count as total_comments %}
     <h2>
       {{ total_comments }} comment{{ total_comments| pluralize }}:
     </h2>
     {% endwith %}

    {% for comment in comments %}
      <div class="comment">
        <p class="info">
          Comment {{ forloop.counter }} by {{ comment.name }}
          {{ comment.created }}
      </p>
        {{ comment.body|linebreaks }}
      </div>
       {% empty %}
      <p>There are no comments yet.</p>
    {% endfor %}
    {% if new_comment %}
      <h2>Your comment has been added.</h2>
    {% else %}
       <h2>Add a new comment</h2>
       <form method="post">
         {{ comment_form.as_p }}
         {% csrf_token %}
         <p><input type="submit" value="Add comment"></p>
       </form>
    {% endif %}   
  {% endblock body %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

   {% block title %}
   My Blog
   {% endblock %}

   {% block body %}
     <h1>Introduction to QuerySets in Django</h1>
     {% for post in posts %}
       <h2>
         <a href="{{ post.get_absolute_url }}">
           {{ post.title }}
         </a>
       </h2>
       <p class="date">
         Published {{ post.publish }} by {{ post.author }}
       </p>
       {{ post.body|truncatewords:30|linebreaks }}
     {% endfor %}

     {% include "blog/pagination.html" with page=posts %}

     <a href={% url 'blog:createpost' %}>
      <input type='submit' value='Add new Post'> 
     </a>
   {% endblock body %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
Share Post
{% endblock %}

{% block body %}
    {% if sent %}
        <h1>E-mail succesfully sent</h1>
        <p>"{{ post.title }}" was succesfully sent to {{ form.cleaned_data.recepient }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by email</h1>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}
    
    

blog/templates/create.html
{% load static %}
<html>

    <head>
        Create a blog Post
        <link href="{% static 'css/create.css' %}" rel="stylesheet">
    </head>

    <body>
        <h1>Create a Post</h1>
        <form action="" method="POST">
        {% csrf_token %}
        <label>
        <label class="form-label">Title:</label>        
        <input type='text' name='title'/><br>
        <label class="form-label">Author:</label>        
        <input type='text' name='author_name' /><br>
        <label class="form-label">Body:</label>        
        <textarea name='content'></textarea><br>

        <input type='submit' value='Post'/>
        </form>
    </body>
</html>